version: '3.5' 

services: 

    devopsdockeruh_simple-web-service: 
      image: devopsdockeruh/simple-web-service:alpine
      build: . 
      volumes: 
        - ./text.log://usr/src/app/text.log
      container_name: simple-web-service-2.1